In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('StudentsPerformance.csv')

In [3]:
data.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group C            some high school  free/reduced   
1  female        group B                 high school  free/reduced   
2  female        group B            some high school  free/reduced   
3  female        group B                some college      standard   
4  female        group C                some college  free/reduced   

  test preparation course  math score  reading score  writing score  
0                    none           0             17             10  
1                    none           8             24             23  
2                    none          18             32             28  
3                    none          11             38             32  
4                    none          22             39             33

In [6]:
data.isna().any()

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course        False
math score                     False
reading score                  False
writing score                  False
dtype: bool

# 1)

In [15]:
data['gender'].value_counts()

female    518
male      482
Name: gender, dtype: int64

There are 518 female and 482 male students.

# 2)

In [20]:
data['parental level of education'].value_counts()

some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: parental level of education, dtype: int64

Out of the 1000 students more than 821 students' parents has completed High School and 177 students parents has completed college.

# 3)

In [25]:
data.groupby('gender').mean()

math score  reading score  writing score
gender                                          
female   63.376448      72.590734      72.467181
male     68.821577      65.545643      63.446058

By comparing the average we can understand that male students have scored higher than female students in maths while female students have scored more in reading and writing.

In [26]:
data.groupby('test preparation course').mean()

math score  reading score  writing score
test preparation course                                          
completed                  69.96648      74.175978      74.684358
none                       63.78972      66.417445      64.457944

By comparing the average we can understand that students who have completed test preparation course have scored higher marks in all the subjects than those who have not completed it.

# 4)

In [30]:
data.groupby('gender').var()

math score  reading score  writing score
gender                                          
female  256.958593     207.677438     220.369327
male    211.889097     200.211010     202.413924

Female studens have higher score variation than male students which means that female students mark distributuion is more dispersed.

In [31]:
data.groupby('test preparation course').var()

math score  reading score  writing score
test preparation course                                          
completed                210.884027     183.265864     175.202612
none                     246.668662     213.419851     226.251739

Similarly students who have not completed the test preparation course has higher score variance compared to students who have completed the course.

# 5)

In [36]:
top=data['math score'].quantile(q=0.75)
data[data['math score'].ge(top)]



gender race/ethnicity parental level of education         lunch  \
414  female        group A                 high school  free/reduced   
415  female        group B             master's degree  free/reduced   
416  female        group B           bachelor's degree  free/reduced   
417  female        group B             master's degree      standard   
418  female        group B                 high school      standard   
..      ...            ...                         ...           ...   
995    male        group E                some college      standard   
996    male        group A                some college      standard   
997    male        group D                some college      standard   
998    male        group E          associate's degree  free/reduced   
999    male        group E           bachelor's degree      standard   

    test preparation course  math score  reading score  writing score  
414               completed          77             88             85  
415               completed          77             97             94  
416                    none          77             85             87  
417                    none          77             90             84  
418               completed          77             82             89  
..                      ...         ...            ...            ...  
995               completed          99             87             81  
996               completed         100             96             86  
997               completed         100             97             99  
998               completed         100            100             93  
999               completed         100            100            100  

[255 rows x 8 columns]

These are the top 25% students in maths exam